name: wewiins-kc-dev

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: wewiins-kc-dev
      KC_BOOTSTRAP_ADMIN_PASSWORD: wewiins-kc-password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KC_HEALTH_ENABLED: true
      KC_HTTP_MANAGEMENT_HEALTH_ENABLED: true
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    command: start-dev --import-realm
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers/
    depends_on:
      - postgres
    networks:
      - keycloak-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - keycloak-network
    depends_on:
      - keycloak

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8181:8080"
    env_file:
      - ./api/.env.dev
    volumes:
      - ./api/src:/api/src
    networks:
      - keycloak-network
    depends_on:
      - keycloak
      - postgres

volumes:
  keycloak-postgres-data:

networks:
  keycloak-network:
    driver: bridge